### ISSUE TITLE
Prevent hltd to start on zombie FUs

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/hltd#57]
After yesterday's hltd update, 3 FUs which should not be used came back alive and created box info files. The hltd on the BU failed to properly talk to them. One should device a way to inhibit the start of the hltd on "blacklisted" FUs.

**Comment by smorovic** [comment]
This is not tripping hltd on BU anymore.
Next major version, hltd 1.7 will include a version number which we can bump as needed (interface between BU <-> FU hltd change). This will exclude machines or appliances that don't get the necessary update, and also alert of situations where new rpms are pushed to FUs, but forgotten to be pushed to BUs, and similar.
